### ISSUE TITLE
Replace substr with substring?

### ISSUE THREAD

**Issue by kbondanza** [hamlim/react-code-editor#2]
Hi @hamlim,

I was wondering if `String.prototype.substr` should be replaced with `String.prototype.substring`?

https://github.com/hamlim/react-code-editor/blob/master/src/index.js#L5

MDN states that `String.prototype.substr` is a legacy function, not part of the core JavaScript language and should be avoided. MDN suggests using `String.prototype.substring` as a replacement if possible.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substring

**Comment by hamlim** [comment]
Yea it should be replaced. Most likely I pulled it from stackoverflow 🤦‍♂️

**Comment by kbondanza** [comment]
Ok thanks! I can put up a PR later today, if you would like.

**Comment by kbondanza** [comment]
Hey Matt,

Silly question, how would you suggest testing any updates to this package?

Thanks!

**Comment by kbondanza** [comment]
Created this PR: https://github.com/hamlim/react-code-editor/pull/3
