### ISSUE TITLE
Add cmd/ctrl f for formatting?

### ISSUE THREAD

**Issue by kbondanza** [hamlim/react-code-editor#4]
I was wondering if it would make sense to add cmd/ctrl f for formatting?

**Comment by hamlim** [comment]
Yea I think that makes sense in addition to Command / control + s for formatting. I'm also going to be moving this package into my `projects` repo soon.

**Comment by hamlim** [comment]
Moved this package over to my projects repo and added this suggestion, will publish as 1.0.0 soon
